Repository SpartaFinalProjectAndroid/OFFROADER, pull requests merged in 2024-03, with the labels that each got.

#97 [Feat] 플로팅 액션 버튼 버블 자유이동 추가 / 챗봇 안내문구 추가
  app/src/main/java/com/ing/offroader/ui/activity/add_post/AddPostActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/chatbot/ChatbotActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/main/MainActivity.kt
  app/src/main/java/com/ing/offroader/ui/fragment/mydetail/LvDialogFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/mydetail/MyDetailFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/sanlist/SanListFragment.kt
  app/src/main/res/drawable/ic_chat_bg.png
  app/src/main/res/drawable/ic_chat_bubble.png
  app/src/main/res/drawable/ic_info.png
  app/src/main/res/drawable/ic_post_camera.png
  app/src/main/res/drawable/ic_post_list.png
  app/src/main/res/drawable/ic_post_photo.png
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/activity_chatbot.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_lv.xml
  app/src/main/res/layout/fragment_my_detail.xml
  app/src/main/res/layout/item_chatbot.xml
  app/src/main/res/values/strings.xml
Labels: refector

#98 [Ref] 챗봇 자연스러운 답장 및 등산 외 질문 거부 / [Layout] 챗봇 입력창 변경
  app/src/main/java/com/ing/offroader/data/repository/AiRepository.kt
  app/src/main/java/com/ing/offroader/data/repository/SanListRepository.kt
  app/src/main/java/com/ing/offroader/ui/activity/chatbot/ChatbotActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/chatbot/adapter/ChatAdapter.kt
  app/src/main/java/com/ing/offroader/ui/activity/chatbot/database/ChatUiState.kt
  app/src/main/java/com/ing/offroader/ui/activity/chatbot/viewmodel/ChatBotViewModel.kt
  app/src/main/java/com/ing/offroader/ui/activity/main/MainActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/sandetail/SanDetailActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/sandetail/SanDetailDTO.kt
  app/src/main/java/com/ing/offroader/ui/fragment/home/HomeUiState.kt
  app/src/main/res/layout/activity_chatbot.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_detail.xml
  app/src/main/res/layout/item_chatbot.xml
  app/src/main/res/raw/ani_chat_loading.json
Labels: refector

#99 [Feature/community] 커뮤니티 수정 및 중복 게시물 버그 수정
  app/src/main/java/com/ing/offroader/data/model/addpost/EditPostDTO.kt
  app/src/main/java/com/ing/offroader/ui/activity/add_post/AddPostActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/add_post/AddPostUiState.kt
  app/src/main/java/com/ing/offroader/ui/activity/add_post/AddPostViewModel.kt
  app/src/main/java/com/ing/offroader/ui/activity/add_post/PostRepository.kt
  app/src/main/java/com/ing/offroader/ui/activity/main/adapters/RadioListAdapter.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostAdapter.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostViewModel.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/CommunityFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/adapter/CommunityAdapter.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/model/PostDTO.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/ing/offroader/ui/fragment/mydetail/MyDetailFragment.kt
  app/src/main/res/drawable/ic_delete.png
  app/src/main/res/drawable/ic_edit.png
  app/src/main/res/drawable/ic_more.png
  app/src/main/res/drawable/ic_report.png
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/bottom_sheet_my.xml
  app/src/main/res/layout/bottom_sheet_other.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#100 [Feat] Blur
  app/src/main/java/com/ing/offroader/ui/fragment/mydetail/MyDetailFragment.kt
  app/src/main/res/layout/fragment_my_detail.xml
Labels: enhancement

#102 [Feature/community] 커뮤니티 버그 수정 (대용량 파일 업로드 실패)
  app/build.gradle.kts
  app/src/main/java/com/ing/offroader/ui/activity/add_post/PostRepository.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostAdapter.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/CommunityFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/adapter/CommunityAdapter.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/model/PostDTO.kt
  app/src/main/java/com/ing/offroader/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/mydetail/MyDetailFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/sanlist/SanListFragment.kt
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/values/strings.xml
Labels: fix

#103 탭 레이아웃, 뷰 페이저, 모션 레이아웃 수정
  app/src/main/java/com/ing/offroader/ui/activity/main/MainActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/main/adapters/RadioListAdapter.kt
  app/src/main/java/com/ing/offroader/ui/activity/main/adapters/ViewPagerAdapter.kt
  app/src/main/res/color/nav_item_color.xml
  app/src/main/res/drawable/ic_tab_community_unselected.png
  app/src/main/res/drawable/ic_tab_home_unselected.png
  app/src/main/res/drawable/ic_tab_map_unselected.png
  app/src/main/res/drawable/ic_tab_my_unselected.png
  app/src/main/res/drawable/ic_tab_san_unselected.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_radio_channel_list.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/activity_main_scene.xml
Labels: fix

#106 [Fix] 자동 스크롤 폭주 문제 해결
  app/src/main/java/com/ing/offroader/ui/activity/sandetail/SanDetailActivity.kt
Labels: bug, fix

#109 탭 레이아웃 탭 커스텀 뷰로 수정
  app/src/main/java/com/ing/offroader/data/RadioChannelURL.kt
  app/src/main/java/com/ing/offroader/ui/activity/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/custum_tab_button.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/activity_main_scene.xml
Labels: refector

#110 [Feature/community] HOTFIX 글라이드 로딩 되기 전에 액티비티가 꺼지면 충돌되는 문제 해결
  app/src/main/java/com/ing/offroader/data/model/addpost/PostModel.kt
  app/src/main/java/com/ing/offroader/ui/activity/add_post/AddPostActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/add_post/PostRepository.kt
  app/src/main/java/com/ing/offroader/ui/activity/main/MainActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostAdapter.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostViewModel.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/CommunityFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/ing/offroader/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/mydetail/MyDetailFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/mydetail/viewmodel/MyDetailViewModel.kt
  app/src/main/res/layout/fragment_my_detail.xml
Labels: fix

#113 [Feature/community] 게시물 올렸을 때 생기는 버그 픽스 했습니다!
  app/src/main/java/com/ing/offroader/ui/activity/add_post/AddPostActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/add_post/AddPostViewModel.kt
  app/src/main/java/com/ing/offroader/ui/activity/add_post/PostRepository.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostActivity.kt
  app/src/main/java/com/ing/offroader/ui/activity/my_post/MyPostViewModel.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/CommunityFragment.kt
  app/src/main/java/com/ing/offroader/ui/fragment/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/ing/offroader/ui/fragment/home/HomeFragment.kt
Labels: fix
